{
 "title": "GIT DIGGING",
 "time": { "from": "2024-07-20T15:59:07.982Z", "to": "2024-07-24T15:59:07.998Z" },
 "panels": [
  {
   "title": "Bus Factor by Folder (Limited to the first 15)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH folder_commits_by_author AS (SELECT folder_commits.folder, commit_author.name as author, count(*) as commits\nFROM (SELECT authors.name, commits.id as commit_id\n\tFROM authors\n\tRIGHT JOIN commits ON commits.author = authors.id) commit_author\nRIGHT JOIN\n\t(SELECT files_and_folders.folder as folder, files_commits.commit_id as commit_id\n\tFROM files_commits\n\tRIGHT JOIN\n\t    (SELECT filename, folders.folder as folder, files.id as file_id\n\t\tFROM files\n\t\tLEFT JOIN\n\t\t\t(SELECT folder\n\t\t\tFROM\n\t\t\t\t(SELECT substring (filename, '.*(?=\\/[^\\/]*)') as folder, count(*) as counted\n\t\t\t\tFROM files\n\t\t\t\tWHERE filename NOT LIKE '%.git%'\n\t\t\t\tAND filename NOT LIKE '%images%'\n\t\t\t\tAND filename NOT LIKE '%docs%'\n\t\t\t\tAND filename NOT LIKE '%assets%'\n\t\t\t\tGROUP BY folder)\n\t\t\tWHERE counted > 5) folders\n\t\tON files.filename LIKE CONCAT(folders.folder, '%')\n\t\tWHERE folder NOT LIKE '.') files_and_folders ON files_and_folders.file_id = files_commits.file_id) folder_commits\nON folder_commits.commit_id = commit_author.commit_id\nGROUP BY folder, author)\n\nSELECT folder_commits_by_author.folder, substring(folder_commits_by_author.folder from '[^\\/]+$') as folder_short, count(*) as bus_factor, ARRAY_AGG(author) as authors\nFROM folder_commits_by_author\nLEFT JOIN\n\t(SELECT folder, SUM(commits) as commits_on_folder\n\tFROM folder_commits_by_author\n\tGROUP BY folder) folder_commits ON folder_commits.folder = folder_commits_by_author.folder\nWHERE commits/folder_commits.commits_on_folder > 0.1\nOR commits > 5\nGROUP BY folder_commits_by_author.folder\nORDER BY bus_factor"
    }
   ]
  },
  {
   "title": "Folders with a bus factor below the thereshold",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as count_pet\r\nFROM (WITH folder_commits_by_author AS (SELECT folder_commits.folder, commit_author.name as author, count(*) as commits\r\nFROM (SELECT authors.name, commits.id as commit_id\r\n\tFROM authors\r\n\tRIGHT JOIN commits ON commits.author = authors.id) commit_author\r\nRIGHT JOIN\r\n\t(SELECT files_and_folders.folder as folder, files_commits.commit_id as commit_id\r\n\tFROM files_commits\r\n\tRIGHT JOIN\r\n\t    (SELECT filename, folders.folder as folder, files.id as file_id\r\n\t\tFROM files\r\n\t\tLEFT JOIN\r\n\t\t\t(SELECT folder\r\n\t\t\tFROM\r\n\t\t\t\t(SELECT substring (filename, '.*(?=\\/[^\\/]*)') as folder, count(*) as counted\r\n\t\t\t\tFROM files\r\n\t\t\t\tWHERE filename NOT LIKE '%.git%'\r\n\t\t\t\tAND filename NOT LIKE '%images%'\r\n\t\t\t\tAND filename NOT LIKE '%docs%'\r\n\t\t\t\tAND filename NOT LIKE '%assets%'\r\n\t\t\t\tGROUP BY folder)\r\n\t\t\tWHERE counted > 5) folders\r\n\t\tON files.filename LIKE CONCAT(folders.folder, '%')\r\n\t\tWHERE folder NOT LIKE '.') files_and_folders ON files_and_folders.file_id = files_commits.file_id) folder_commits\r\nON folder_commits.commit_id = commit_author.commit_id\r\nGROUP BY folder, author)\r\n\r\nSELECT folder_commits_by_author.folder, substring(folder_commits_by_author.folder from '[^\\/]+$') as folder_short, count(*) as bus_factor, ARRAY_AGG(author) as authors\r\nFROM folder_commits_by_author\r\nLEFT JOIN\r\n\t(SELECT folder, SUM(commits) as commits_on_folder\r\n\tFROM folder_commits_by_author\r\n\tGROUP BY folder) folder_commits ON folder_commits.folder = folder_commits_by_author.folder\r\nWHERE commits/folder_commits.commits_on_folder > 0.1\r\nOR commits > 5\r\nGROUP BY folder_commits_by_author.folder\r\nORDER BY bus_factor)\r\nWHERE bus_factor <= 3;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Commit frequency change in the last half year",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT commits_full_timespan.fullfilename, commits_full_timespan.filename, commits_half_timespan.commits AS commits_half_timespan,  CAST(commits_full_timespan.commits AS FLOAT)/2 AS expected_commits_half_timespan, commits_full_timespan.commits AS commits_full_timespan\r\nFROM (\r\n\tSELECT files.id as file_id, files.filename as fullfilename, substring(files.filename from '[^\\/]*$') as filename, filecount.counted as commits\r\n\tFROM files\r\n\tINNER JOIN (\r\n\t\tSELECT files_commits.file_id, COUNT(*) as counted\r\n\t\tFROM files_commits\r\n\t\tINNER JOIN (\r\n\t\t\tSELECT commits.id AS commit_id\r\n\t\t\tFROM commits\r\n\t\t\tINNER JOIN (\r\n\t\t\t\tSELECT id, name\r\n\t\t\t\tFROM authors\r\n\t\t\t\tWHERE name NOT LIKE '%[bot]%'\r\n\t\t\t) no_bots ON commits.author = no_bots.id \r\n\t\t\tWHERE commits.datetime < NOW ()\r\n\t\t\tAND commits.datetime > NOW() - INTERVAL '183 days'\r\n\t\t) relevant_commits on relevant_commits.commit_id = files_commits.commit_id\r\n\t\tGROUP BY files_commits.file_id\r\n\t\tORDER BY counted DESC\r\n\t) filecount ON filecount.file_id = files.id\r\n\tWHERE files.filename NOT LIKE '%.adoc' AND files.filename NOT LIKE '%.md'\r\n) commits_half_timespan\r\nRIGHT JOIN (\r\n\tSELECT files.id as file_id, files.filename as fullfilename, substring(files.filename from '[^\\/]*$') as filename, filecount.counted as commits\r\n\tFROM files\r\n\tINNER JOIN (\r\n\t\tSELECT files_commits.file_id, COUNT(*) as counted\r\n\t\tFROM files_commits\r\n\t\tINNER JOIN (\r\n\t\t\tSELECT commits.id AS commit_id\r\n\t\t\tFROM commits\r\n\t\t\tINNER JOIN (\r\n\t\t\t\tSELECT id, name\r\n\t\t\t\tFROM authors\r\n\t\t\t\tWHERE name NOT LIKE '%[bot]%'\r\n\t\t\t) no_bots ON commits.author = no_bots.id \r\n\t\t\tWHERE commits.datetime < NOW ()\r\n\t\t\tAND commits.datetime > NOW() - INTERVAL '1 year'\r\n\t\t) relevant_commits on relevant_commits.commit_id = files_commits.commit_id\r\n\t\tGROUP BY files_commits.file_id\r\n\t\tORDER BY counted DESC\r\n\t) filecount ON filecount.file_id = files.id\r\n\tWHERE files.filename NOT LIKE '%.adoc' AND files.filename NOT LIKE '%.md'\r\n\tORDER BY counted DESC\r\n\tLIMIT 10\r\n) commits_full_timespan\r\nON commits_half_timespan.file_id = commits_full_timespan.file_id\r\nORDER BY commits_full_timespan.commits DESC"
    }
   ]
  },
  {
   "title": "Most edited files",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "\tSELECT files.filename as fullfilename, substring(files.filename from '[^\\/]*$') as filename, filecount.counted as commits\n\tFROM files\n\tINNER JOIN\n\t\t(SELECT files_commits.file_id, COUNT(*) as counted\n\t\tFROM files_commits\n\t\tLEFT JOIN\n\t\t\t(SELECT commits.id \n\t\t\tFROM commits\n\t\t\tLEFT JOIN (\n\t\t\t\tSELECT id, name\n\t\t\t\tFROM authors\n\t\t\t\tWHERE name NOT LIKE '%[bot]%'\n\t\t\t\t) no_bots ON commits.author = no_bots.id \n\t\t\tWHERE commits.datetime < NOW () AND commits.datetime > NOW() - INTERVAL '10 days'\n\t\t\t) relevant_commits on relevant_commits.id = files_commits.file_id\n\t\tGROUP BY files_commits.file_id\n\t    ORDER BY counted DESC\n\t\t) filecount ON filecount.file_id = files.id\n\tWHERE files.filename NOT LIKE '%.adoc' AND files.filename NOT LIKE '%.md'\n\tORDER BY counted DESC\n\tLIMIT 10"
    }
   ]
  },
  {
   "title": "File Coupling",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH files_commits_with_filename AS (\n    SELECT commits.id AS commit_id, commits.hash, files_commits.file_id, files_commits.filename, files_commits.counted_commits AS counted_commits\n\tFROM commits\n\tINNER JOIN\n\t\t(SELECT commit_id, files_with_commits_counter.file_id, filename, files_with_commits_counter.counted_commits\n\t\tFROM files_commits\n\t\tINNER JOIN (\n\t\t\tSELECT count(*) AS counted_commits, files.id AS file_id, filename\n\t\t\tFROM files_commits\n\t\t\tLEFT JOIN files ON files_commits.file_id = files.id\n\t\t\tGROUP BY files.id, filename\n\t\t) files_with_commits_counter ON files_commits.file_id = files_with_commits_counter.file_id\n\tWHERE filename NOT LIKE '%docs%'\n\tAND filename NOT LIKE '%.adoc'\n\tAND files_with_commits_counter.counted_commits > 5) files_commits\n\tON files_commits.commit_id = commits.id\n)\n\nSELECT * FROM\n(SELECT lefti.filename AS filename_left, lefti.counted_commits AS commits_left, count(*) AS common_commits, righti.counted_commits AS commits_right, righti.filename AS filename_right, ARRAY_AGG(lefti.hash) AS commits\n\tFROM files_commits_with_filename AS lefti\nLEFT JOIN files_commits_with_filename AS righti ON lefti.commit_id = righti.commit_id\nWHERE lefti.file_id < righti.file_id\nGROUP BY lefti.file_id, righti.file_id, lefti.filename, righti.filename, lefti.counted_commits, righti.counted_commits\nORDER BY common_commits DESC)\nWHERE common_commits > 5\nAND ((CAST (common_commits AS float))/ (CAST (commits_left AS FLOAT)) > 0.3\n\tOR (CAST (common_commits AS float))/ (CAST (commits_right AS FLOAT)) > 0.3)\n"
    }
   ]
  }
 ]
}